apiVersion: apps/v1
kind: Deployment
metadata:
  name: nutritrack
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nutritrack
  template:
    metadata:
      labels:
        app: nutritrack
    spec:
      containers:
        - name: nutritrack
          image: us-central1-docker.pkg.dev/nutritrack-651/nutritrack-fullstack/nutritrack-image:<GITHUB_SHA>
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: backend-env
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: nutritrack-service
spec:
  type: LoadBalancer
  selector:
    app: nutritrack
  ports:
    - port: 80
      targetPort: 5000
