name: CD - Docker Build

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  docker-build:
    name: Docker PR Build Check 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image (PR validation)
        run: |
          IMAGE_TAG=temp-build:pr-check
          echo "Building Docker image with tag: $IMAGE_TAG"

          docker build -t $IMAGE_TAG \
            --build-arg VITE_GOOGLE_CLIENT_ID=${{ secrets.VITE_GOOGLE_CLIENT_ID }} \
            --build-arg VITE_NUTRITIONIX_APP_ID=${{ secrets.VITE_NUTRITIONIX_APP_ID }} \
            --build-arg VITE_NUTRITIONIX_API_KEY=${{ secrets.VITE_NUTRITIONIX_API_KEY }} \
            --build-arg VITE_BACKEND_URL=${{ secrets.VITE_BACKEND_URL }} \
            --build-arg VITE_PORT=5000 .

      - name: Success message
        run: echo "Docker image built successfully — PR is good to go!"
