name: Deploy to GKE

on:
  workflow_run:
    workflows: ["Node.js CI"]
    types:
      - completed

env:
  PROJECT_ID: nutritrack-651
  CLUSTER_NAME: nutritrack-cluster
  CLUSTER_REGION: us-central1
  IMAGE_NAME: nutritrack-fullstack
  IMAGE_TAG: us-central1-docker.pkg.dev/nutritrack-651/nutritrack-fullstack

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up gcloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker

      - name: Build and Push Docker Image to Artifact Registry
        run: |
          docker build -t $IMAGE_TAG:$GITHUB_SHA \
            --build-arg VITE_GOOGLE_CLIENT_ID=${{ secrets.VITE_GOOGLE_CLIENT_ID }} \
            --build-arg VITE_NUTRITIONIX_APP_ID=${{ secrets.VITE_NUTRITIONIX_APP_ID }} \
            --build-arg VITE_NUTRITIONIX_API_KEY=${{ secrets.VITE_NUTRITIONIX_API_KEY }} \
            --build-arg VITE_BACKEND_URL=${{ secrets.VITE_BACKEND_URL }} \
            --build-arg VITE_PORT=5000 .

          docker push $IMAGE_TAG:$GITHUB_SHA

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials $CLUSTER_NAME --region $CLUSTER_REGION

      - name: Deploy to GKE
        run: kubectl apply -f k8s/deployment.yaml
